SELECT ID,EMAIL,PASSWORD,NAME,REGDATE FROM MEMBER;
INSERT INTO MEMBER(EMAIL,PASSWORD,NAME,REGDATE) VALUES ('test2@test2.co.kr', '2222', 'test2', '2020-09-28');


UPDATE MEMBER SET email WHERE id = ?

DELETE FROM MEMBER WHERE id = 10;